apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: wuujy7pb8-go 
  janus-idp.io/tekton: wuujy7pb8-go
  backstage.io/kubernetes-id: wuujy7pb8-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: wuujy7pb8-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  